# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38560d1ff9768b60c825300a7acea2a9cbf4544296af11457fec267c8fde216b14e36bc420a8e4045b7868d468c4907b30eb0b74b2278cafc226e1b9d52436da

test:
  secret_key_base: 3aa2ff0e501c90f289153604e0b109ccbcf9b76132fc16fe77d72a84a64d9353984f6de538c6ada8b7f7c870f2c9e5fe31ff43aa46f0bf8e9ca3c8996af81b54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
